default: &default
 adapter: postgresql
development:
 <<: *default
 database: development_scrapper
test:
 <<: *default
 database: test_scrap
production:
 <<: *default
 database: production_scrapper



